#!/usr/bin/perl -s

#!/bin/csh -f
#!/usr/bin/perl -s
#eval 'exec perl -s -x -S $0 $*:q'
# if 0;

# Do some perl operation on a bunch of files, editing those files in place.

if (($ARGV[0] eq "") || ($ARGV[1] eq "")) {
    print "Usage: replace perlexpr file [file ...]\n";
    exit(1);
}

$op = shift;

print "Applying '$op' to\n";
print "@ARGV\n";

foreach $i (0 .. $#ARGV) {
    $filename = $ARGV[$i];
    $filenamebak = $filename . ".bak";
    if (-d $filename) {
      print "Cannot process directory $filename\n";
      next;
    }

    # rename the file to .bak
    if (!rename ($filename, $filenamebak)) {
	die "Cannot backup $filename : $!";
	exit(1);
    }

    # open the new .bak file for input
    if (!open(INPUT, $filenamebak)) {
	die "Cannot open $filenamebak : $!";
    }
    # and prepare to write modified contents to the original filename
    open(OUTPUT, "> $filename");

    # do the write
    while (<INPUT>) {
	eval $op;
	print OUTPUT $_;
    }
}
