#!/usr/bin/perl -s
use strict;
use warnings;

# -l automatically chomps the input record, and sets R\ equal to $/.
# I was having problems with ^M (CR) characters showing up randomly

# Do some perl operation on a bunch of files, editing those files in place.

if (($ARGV[0] eq "") || ($ARGV[1] eq "")) {
    print "Usage: replace perlexpr file [file ...]\n";
    exit(1);
}

my $op = shift;
my $i = 0;
foreach $i (0 .. $#ARGV) {
    print "Argument ", $i, " = ==>", $ARGV[$i], "<==\n";
}

print "Applying '$op' to\n";
print "@ARGV\n";

foreach $i (0 .. $#ARGV) {
    my $filename = $ARGV[$i];
    my $filenamebak = $filename . ".bak";
    if (-d $filename) {
      print "Cannot process directory $filename\n";
      next;
    }

    # rename the file to .bak
    if (!rename ($filename, $filenamebak)) {
	die "Cannot backup $filename : $!";
	exit(1);
    }

    # open the new .bak file for input
    if (!open(INPUT, $filenamebak)) {
	die "Cannot open $filenamebak : $!";
    }
    # and prepare to write modified contents to the original filename
    open(OUTPUT, "> $filename");

    # do the write
    while (<INPUT>) {
	eval $op;
	print OUTPUT $_;
    }
}
